export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const FETCH_FOLLOWERS_COUNT = 'FETCH_FOLLOWERS_COUNT';
export const SET_FOLLOWERS_COUNT = 'SET_FOLLOWERS_COUNT';
export const CLEAR_FOLLOWERS = 'CLEAR_FOLLOWERS';

export const FETCH_FOLLOWINGS = 'FETCH_FOLLOWINGS';
export const SET_FOLLOWINGS = 'SET_FOLLOWINGS';
export const FETCH_FOLLOWINGS_COUNT = 'FETCH_FOLLOWINGS_COUNT';
export const SET_FOLLOWINGS_COUNT = 'SET_FOLLOWINGS_COUNT';
export const CLEAR_FOLLOWINGS = 'CLEAR_FOLLOWINGS';
