export const FETCH_MOVIE_REVIEWS = 'FETCH_MOVIE_REVIEW';
export const FETCH_MOVIE_REVIEWS_SUCCESS = 'FETCH_MOVIE_REVIEW_SUCCESS';
export const SET_REACTION = 'SET_REACTION';
export const SET_REACTION_SUCCESS = 'SET_REACTION_SUCCESS';
export const SET_REACTION_FAILURE = 'SET_REACTION_FAILURE';
