export const FETCH_RECOMMENDED = 'FETCH_RECOMMENDED';
export const SET_RECOMMENDED = 'SET_RECOMMENDED';
export const SET_RECOMMENDED_REACTION = 'SET_RECOMMENDED_REACTION';
export const SET_RECOMMENDED_REACTION_SUCCESS =
	'SET_RECOMMENDED_REACTION_SUCCESS';
