export const START_FETCH_SEARCH_FILMS = 'START_FETCH_SEARCH_FILMS';
export const FINISH_FETCH_SEARCH_FILMS = 'FINISH_FETCH_SEARCH_FILMS';
export const ERROR_FETCH_SEARCH_FILMS = 'ERROR_FETCH_SEARCH_FILMS';
export const SEND_TOKEN_TO_SERVER = 'SEND_TOKEN_TO_SERVER';
