export const START_FETCH_SEARCH_FILMS = 'START_FETCH_SEARCH_FILMS';
export const FINISH_FETCH_SEARCH_FILMS = 'FINISH_FETCH_SEARCH_FILMS';
export const ERROR_FETCH_SEARCH_FILMS = 'ERROR_FETCH_SEARCH_FILMS';
export const SEND_TOKEN_TO_SERVER = 'SEND_TOKEN_TO_SERVER';
export const SET_NOTIFICATION_IS_READ = 'SET_NOTIFICATION_IS_READ';
export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS';
export const GET_UNREAD_NOTIFICATIONS_SUCCESS =
	'GET_UNREAD_NOTIFICATIONS_SUCCESS';
