export const GET_USER_EVENTS = 'GET_USER_EVENTS';
export const GET_USER_EVENTS_SUCCESS = 'GET_USER_EVENTS_SUCCESS';
export const START_UPLOAD_USER_EVENTS = 'START_UPLOAD_USER_EVENTS';
export const FINISH_UPLOAD_USER_EVENTS = 'FINISH_UPLOAD_USER_EVENTS';
export const DELETE_OWN_USER_EVENT = 'DELETE_OWN_USER_EVENT';
export const UPDATE_USER_EVENT = 'UPDATE_USER_EVENT';
