export const START_UPLOAD_AVATAR = "START_UPLOAD_AVATAR";
export const FINISH_UPLOAD_AVATAR = "FINISH_UPLOAD_AVATAR";
export const ERROR_UPLOAD_AVATAR = "ERROR_UPLOAD_AVATAR";
export const SET_TEMP_AVATAR = "SET_TEMP_AVATAR";
export const CANCEL_TEMP_AVATAR="CANCEL_TEMP_AVATAR";