export const FETCH_USER_RATES = 'FETCH_USER_RATES';
export const FETCH_USER_RATES_SUCCESS = 'FETCH_USER_RATES_SUCCESS';
export const SAVE_USER_RATE = 'SAVE_USER_RATE';
export const SAVE_USER_RATE_SUCCESS = 'SAVE_USER_RATE_SUCCESS';
export const DELETE_USER_RATE = 'DELETE_USER_RATE';
export const DELETE_USER_RATE_SUCCESS = 'DELETE_USER_RATE_SUCCESS';
