export const FETCH_CHATS = 'FETCH_CHATS';
export const SET_CHATS = 'SET_CHATS';
export const CREATE_CHAT = 'CREATE_CHAT';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const ADD_MESSAGE_STORE = 'ADD_MESSAGE_STORE';
export const DELETE_MESSAGE_STORE = 'DELETE_MESSAGE_STORE';
export const UPDATE_MESSAGE_STORE = 'UPDATE_MESSAGE_STORE';

export const READ_MESSAGES = 'READ_MESSAGES';
export const READ_MESSAGES_STORE = 'READ_MESSAGES_STORE';
export const ADD_UNREAD_MESSAGE = 'ADD_UNREAD_MESSAGE';
