export const SEARCH_MOVIE_TITLE = 'SEARCH_MOVIE_TITLE';
export const SEARCH_MOVIE_TITLE_SUCCESS = 'SEARCH_MOVIE_TITLE_SUCCESS';
export const DELETE_SEARCH_DATA = 'DELETE_SEARCH_DATA';
export const FETCH_MOVIE_PROPERTIES = 'FETCH_MOVIE_PROPERTIES';
export const FETCH_MOVIE_PROPERTIES_SUCCESS = 'FETCH_MOVIE_PROPERTIES_SUCCESS';
export const DELETE_SELECTED_MOVIE = 'DELETE_SELECTED_MOVIE';
