export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const SET_SURVEYS = 'SET_SURVEYS';
export const ADD_SURVEY = 'ADD_SURVEY';
export const UPDATE_SURVEY = 'UPDATE_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const RECREATE_SURVEY = 'RECREATE_SURVEY';
export const FETCH_USER_SURVEYS = 'FETCH_USER_SURVEYS';
