export const FETCH_STORIES = 'FETCH_STORIES';
export const SET_STORIES = 'SET_STORIES';
export const SET_CAPTION_NEWSTORY = 'SET_CAPTION_NEWSTORY';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';
export const CHANGE_ACTIVITY = 'CHANGE_ACTIVITY';
export const CREATE_STORY = 'CREATE_STORY';
