export const FETCH_STORIES = 'FETCH_STORIES';
export const SET_STORIES = 'SET_STORIES';
export const SET_CAPTION_NEWSTORY = 'SET_CAPTION_NEWSTORY';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';
export const CHANGE_ACTIVITY = 'CHANGE_ACTIVITY';
export const CREATE_STORY = 'CREATE_STORY';
export const ADD_STORY = 'ADD_STORY';
export const RESET_NEW_STORY = 'RESET_NEW_STORY';

export const CREATE_VOTING = 'CREATE_VOTING';
export const SAVE_MOVIE = 'SAVE_MOVIE';
