export const FETCH_USERS = 'FETCH_USERS';
export const SET_USERS = 'SET_USERS';
export const DELETE_USERS = 'DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const DELETE_MOVIES = 'DELETE_MOVIES';
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS';

export const FETCH_POSTS = 'FETCH_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const DELETE_POSTS = 'DELETE_POSTS';
export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS';

export const FETCH_TOPS = 'FETCH_TOPS';
export const SET_TOPS = 'SET_TOPS';
export const DELETE_TOPS = 'DELETE_TOPS';
export const DELETE_TOPS_SUCCESS = 'DELETE_TOPS_SUCCESS';

export const FETCH_STORIES = 'FETCH_STORIES';
export const SET_STORIES = 'SET_STORIES';
export const DELETE_STORIES = 'DELETE_STORIES';
export const DELETE_STORIES_SUCCESS = 'DELETE_STORIES_SUCCESS';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const SET_EVENTS = 'SET_EVENTS';
export const DELETE_EVENTS = 'DELETE_EVENTS';
export const DELETE_EVENTS_SUCCESS = 'DELETE_EVENTS_SUCCESS';

export const FETCH_VOTING = 'FETCH_VOTING';
export const SET_VOTING = 'SET_VOTING';
export const DELETE_VOTING = 'DELETE_VOTING';
export const DELETE_VOTING_SUCCESS = 'DELETE_VOTING_SUCCESS';
