import { MigrationInterface, QueryRunner, getCustomRepository } from "typeorm";
import UserRepository from "../repository/user.repository";
import ReviewRepository from "../repository/review.repository";
import { Review } from "../models/ReviewModel";

export class SeedReviews1566319951202 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    const reviewTextsSeed = [
      "Quentin Tarantino’s “Inglourious Basterds” is a big, bold, audacious war movie that will annoy some, startle others and demonstrate once again that he’s the real thing, a director of quixotic delights. For starters (and at this late stage after the premiere in May at Cannes, I don’t believe I’m spoiling anything), he provides World War II with a much-needed alternative ending. For once the basterds get what’s coming to them.From the title, ripped off from a 1978 B-movie, to the Western sound of the Ennio Morricone opening music to the key location, a movie theater, the film embeds Tarantino’s love of the movies. The deep, rich colors of 35mm film provide tactile pleasure. A character at the beginning and end, not seen in between, brings the story full circle. The “basterds” themselves, savage fighters dropped behind Nazi lines, are an unmistakable nod to the Dirty Dozen. And above all, there are three iconic characters, drawn broadly and with love: the Hero, the Nazi and the Girl. These three, played by Brad Pitt, Christoph Waltz and Melanie Laurent, are seen with that Tarantino knack of taking a character and making it a Character, definitive, larger than life, approaching satire in its intensity but not — quite — going that far. Let’s say they feel bigger than most of the people we meet in movies.",
      'John Wick has a very simple, maybe even laughable plot. It is a typical guy takes his revenge movie. It can be easily summarized as "Keanu gets pissed and shoots people in the face for 101 minutes" but the thing is you actually can see it is really Keanu who is doing it. Instead of shaky cameras and dozens of superfast cuts, you can see kick-ass long takes which are amazingly choreographed. Since this is their first film, the director duo has a few problems with storytelling but I am glad that they made me realize how much I miss watching an action movie and actually see whats going on.',
      "The movie really live up audience expectation. Its dumb, ridiculous,fun, and crazy too. This why audience watch this kind of movie because of its entertainment value. The movie really offer audience a lot this time. You got Dwayne Johnson and Jason Statham bicker all the time like husband and wife, ridiculous action sequence, and powerful family theme which I think very relatable for some audience. The movie also have surprise appearance by some popular actor which I think gonna get people excited more. Overall, its very enjoyable dumb flick action movie that definitely live up our expectation",
      "I was a mere child when I watched LOTR franchise and I still liked it. Ever since, year by year, I grew fonder and fonder of the movies and they remain, and probably forever will, one of my favorite movies of all time. Ive read all the books countless times (including Hobit) and when I saw that Hobbit was coming into the cinema, my mind was entirely wiped away from its existence due to excitement that entered me. Now, movie review. As expected from Peter - almost flawless masterpiece. Given that he had a lot of material to work with, I imagine it was quite hard to put everything together for the scenery - yet he did it, once more. He captured the feeling of the book and transcended it onto a screen; of course, it was not solely his credit, to not be mistaken. The acting was amazing - perfectly fitting into fantasy style. The chemistry between actors was more than just the obvious - you could actually feel their interactions and live the story. Yes, it was that good. I have no need to begin writing about camera work and all that comes with it; locations were beautiful, effects and colors were mixed perfect, a soundtrack that followed through pattered with what was going on perfectly ... it is really one of those moments when you simply cant say enough because you know, regardless of how many words you put in, you still wont be able to describe things the way you felt them. I have only one thing to say: congratulations Mr. Jackson and rest of the cast.The Hobbit: An Unexpected Journey will become classic without any doubt; I am just glad that I got to be a part of the generation that witnessed the never-dying franchise of Mr. Tolkiens work.",
      "Honestly, the kids involved here are actually pretty funny and they are quite hard to dislike. Each one of them has something unique about themselves and they all have goals they want to accomplish by the end of the film. By far the most compelling character was Tremblay’s Max, who has a massive crush on his classmate Brixlee (Millie Davis). All he wants to do is to attend a party that a fellow student is hosting in order to hopefully tell her how he feels. Nothing is too crazy to believe about the story which was nice to see.",
      "After watching the film a second time, take careful notes on the formal and thematic elements of the film. Then attempt to create a central idea for your review that brings together the film’s formal and thematic elements. If your second viewing does not yield a strong central claim for the review or if you need to take more notes, you may have to watch the film or parts of the film a third time. ",
      "A film, also called a movie or motion picture, is a series of still images on a strip of plastic which, when run through a projector and shown on a screen, creates the illusion of moving images. A film is created by photographing actual scenes with a motion picture camera; by photographing drawings or miniature models using traditional animation techniques; by means of CGI (Computer-generated imagery) and computer animation; or by a combination of some or all of these techniques and other visual effects. The process of filmmaking is both an art and an industry.",
      "Films are cultural artifacts created by specific cultures. They reflect those cultures, and, in turn, affect them. Film is considered to be an important art form, a source of popular entertainment, and a powerful medium for educating—or indoctrinating—citizens. The visual basis of film gives it a universal power of communication. Some films have become popular worldwide attractions by using dubbing or subtitles to translate the dialog into the language of the viewer.",
      'The name "film" originates from the fact that photographic film (also called film stock) has historically been the medium for recording and displaying motion pictures. Many other terms exist for an individual motion picture, including picture, picture show, moving picture, photoplay and flick. The most common term in the United States is movie, while in Europe film is preferred. Terms for the field in general include the big screen, the silver screen, the movies and cinema; the latter is commonly used in scholarly texts and critical essays, especially by European writers. In early years, the word sheet was sometimes used instead of screen.',
      "Use subtitles. Just because you’re using subtitles, it doesn’t mean that you’re cheating because you’re still hearing English audio. If you’re of a lower level, use subtitles in your own language until you feel more comfortable watching the movie without them. If you’re of a more advanced level, challenge yourself a little bit and step out of your comfort zone and watch a movie with English subtitles. You don’t have to follow with them word for word as this can be quite tiring, instead just use them to get the gist (the idea) of something if the speech becomes too fast or the language is too colloquial (casual language) that you can’t understand what the characters are saying.",
      "Break it up. If you find watching the movie in English tiring, break it up a little. Watch the movie in 30 minute parts. After you’ve watched one part, do something else. Grab a drink, eat something, check your inbox, whatever, it doesn’t matter as long as you can remain focused during the parts. Watching a full movie in only English can be really overwhelming and also frustrating especially if you’re straining yourself to understand, which is why it’s a good idea to watch it in smaller parts.",
      "Listen and repeat. The beauty of watching a recorded movie online or on a DVD is that you’re able to pause and go back if you don’t understand – something you can’t do with your English teachers in the classroom. Go back to a part you didn’t understand and say it out loud. Repeat it a few times and read what the subtitles say. Verbally repeating something you hear is a great way of perfecting a natural sounding accent, this is something which is a little bit more difficult in a language classroom as it leaves us feeling silly sometimes – in your own bedroom there’s no need for shame, repeat as much as you like until you get it right!",
      "Watch movies you enjoy. Don’t like drama? Don’t watch them! Don’t like lovey dovey romance? Don’t watch them! There are literally thousands and thousands of movies out there and there’s something for everyone’s taste. Choose movies with the genre (kind of movie e.g. romance, horror) that you prefer as you’re more likely to take something away from it and learn. If you force yourself to watch movies that aren’t the slightest bit interesting to you in terms of story, you’re going to struggle and you may as well head back to your English language lessons if that’s the case.",
      "Every day Chuck talks with the ball (Wilson) to fight his loneliness. Four years later Chuck is still on the island and is fishing off a man-made raft he made with Wilson. Wilson falls into the sea and cannot be rescued leaving Chuck feeling lonely and lost again until he’s rescued by a passing cargo ship. Chuck is taken back home, however, four years later everything has changed and it’s no longer the life he once knew.",
      "Story: This is an animated (cartoon) movie that follows a young boy called Andy. Andy loves playing in his room with his toys. He especially loves to play with his action figure called Woody. When Andy disappears, the toys come to life. Andy’s mom gives him a new toy for his birthday which is called Buzz Lightyear, which becomes Andy’s new favorite toy to play with",
      "Story: This story is set in the future and set in a futuristic nation called Panem. Every year there are two people who are chosen to represent their district in the Hunger Games fight. Those who are chosen are done so by a lottery system. This follows the story of Katniss, a 16-year-old girl, from District 12. It shows her intense training and then how she is suddenly thrown into the fight to represent her area in the 74",
      "Why it’s a great movie for learning English: First of all it’s hilarious (really funny) and it keeps us interested throughout the movie. Because it’s a comedy and we rely a lot on the visuals to understand, it makes it a lot easier to understand the dialogue between the characters. All of the characters in “The Hangover” use everyday English, which makes this movie an awesome way of learning modern American slang which will help you fit into everyday life if you’re planning on moving to the United States. You’ll hear common phrases such as “stag party” (bachelor party) and “all-nighter” (staying up all night without sleep).",
      "Why it’s a great movie for learning English: This is an award winning movie written by Aaron Sorkin. He’s famous for his natural dialogue and funny lines, which makes this movie really enjoyable to watch and of course it’s easy to follow too. Also, almost everyone understands and knows Facebook and you will automatically be able to relate to the movie and not to mention, you’ll also be able to pick up a lot of great English vocabulary related to computers, technology and social networks.",
      "Focus on movies from one country. As you know English is spoken throughout the world in different countries but when you’re trying to learn English it’s better to stick to one area as the language tends to vary as does the accent. Choose the country which interests you most and start with these movies (until you become more confident at least). Most ESL learners prefer to learn English from American movies because they’re more familiar with the culture and the accents tend to be easier to understand compared to other English speaking countries",
      "Watch them with friends. Do you have some buddies who also want to perfect their English skills? Pair up and catch a movie together. Not only are you getting to hang out with your friends, but you’ll also be able to fill each other in on different parts you don’t understand. Want to take it a little further? Grab a coffee after the movie and discuss your opinions and favorite parts of the movie (all in English of course).",
      "eep a movie journal. Heard a phrase or word you loved? Want to be able to use in the future? Write it down! While you watch your movies, pause the video when you hear something that you might find useful in the future and write it down in a journal."
    ];
    const seedFilmsId = ["24918", "955"];

    const users = await getCustomRepository(UserRepository).find();
    reviewTextsSeed.map(async reviewItem => {
      const review = new Review();
      review.text = reviewItem;
      review.movieId =
        seedFilmsId[Math.floor(Math.random() * seedFilmsId.length)];
      review.user = users[Math.floor(Math.random() * users.length)];
      await getCustomRepository(ReviewRepository).save(review);
    });
  }

  public async down(queryRunner: QueryRunner): Promise<any> {}
}
