export const FETCH_MOVIE_LIST = 'FETCH_MOVIE_LIST';
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const SET_MOVIE_SERIES = 'SET_MOVIE_SERIES';
export const CLEAR_ElASTIC_MOVIE_LIST = 'CLEAR_ElASTIC_MOVIE_LIST';
export const SET_ElASTIC_MOVIE_LIST = 'SET_ElASTIC_MOVIE_LIST';
export const FETCH_MOVIE_USER_RATE = 'FETCH_MOVIE_USER_RATE';
export const FETCH_MOVIE_USER_RATE_SUCCESS = 'FETCH_MOVIE_USER_RATE_SUCCESS';
