export const FINISH_SEARCH_ELASTIC_FILMS = 'FINISH_SEARCH_ELASTIC_FILMS';
export const START_SEARCH_ELASTIC_FILMS = 'START_SEARCH_ELASTIC_FILMS';
export const START_UPLOAD_TOP_IMAGE = 'START_UPLOAD_TOP_IMAGE';
export const SET_TOP_IMAGE = 'SET_TOP_IMAGE';
