export const CONTENT_SEARCH_FETCH_ALL = 'CONTENT_SEARCH_FETCH_ALL';
export const CONTENT_SEARCH_FETCH_MOVIE = 'CONTENT_SEARCH_FETCH_MOVIE';
export const CONTENT_SEARCH_FETCH_EVENT = 'CONTENT_SEARCH_FETCH_EVENT';
export const CONTENT_SEARCH_FETCH_TOP = 'CONTENT_SEARCH_FETCH_TOP';
export const CONTENT_SEARCH_FETCH_SURVEY = 'CONTENT_SEARCH_FETCH_SURVEY';
