export const UPDATE_USER_EMAIL = 'SETTINGS:UPDATE_USER_EMAIL';
export const UPDATE_USER_PASSWORD = 'SETTINGS:UPDATE_USER_PASSWORD';
export const DELETE_USER = 'SETTINGS:DELETE_USER';
export const UPDATE_NOTIFICATION_SETTINGS =
	'SETTINGS:UPDATE_NOTIFICATION_SETTINGS';
export const UPDATE_PRIVACY = 'SETTINGS:UPDATE_PRIVACY_SETTINGS';
