export const FINISH_SEARCH_ELASTIC_FILMS = 'FINISH_SEARCH_ELASTIC_FILMS';
export const START_SEARCH_ELASTIC_FILMS = 'START_SEARCH_ELASTIC_FILMS';
export const START_UPLOAD_TOP_IMAGE = 'START_UPLOAD_TOP_IMAGE';
export const SET_TOP_IMAGE = 'SET_TOP_IMAGE';
export const SET_ElASTIC_MOVIE_LIST = 'SET_ElASTIC_MOVIE_LIST';

export const FETCH_TOPS = 'FETCH_TOPS';
export const SET_TOPS = 'SET_TOPS';
export const ADD_TOP = 'ADD_TOP';
export const ADD_TOP_SUCCESS = 'ADD_TOP_SUCCESS';
export const UPDATE_TOP = 'UPDATE_TOP';
export const UPDATE_TOP_SUCCESS = 'UPDATE_TOP_SUCCESS';
export const DELETE_TOP = 'DELETE_TOP';
export const DELETE_TOP_SUCCESS = 'DELETE_TOP_SUCCESS';
