export const LOGIN = "LOGIN";
export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_USER_BY_TOKEN = "FETCH_USER_BY_TOKEN";
export const FETCH_REGISTRATION = "FETCH_REGISTRATION";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";