export const FETCH_USER_WATCH_LIST = 'FETCH_USER_WATCH_LIST';
export const FETCH_USER_WATCH_LIST_SUCCESS = 'FETCH_USER_WATCH_LIST_SUCCESS';
export const SAVE_WATCH_ITEM = 'SAVE_WATCH_ITEM';
export const SAVE_WATCH_ITEM_SUCCESS = 'SAVE_WATCH_ITEM_SUCCESS';
export const MOVE_WATCH_ITEM_TO_WATCHED = 'MOVE_WATCH_ITEM_TO_WATCHED';
export const DELETE_WATCH_ITEM = 'DELETE_WATCH_ITEM';
export const FETCH_WATCH_LIST_STATUS = 'FETCH_WATCH_LIST_STATUS';
export const FETCH_WATCH_LIST_STATUS_SUCCESS =
	'FETCH_WATCH_LIST_STATUS_SUCCESS';
export const ADD_MOVIE_TO_WATCH_LIST = 'ADD_WATCH_ITEM';
export const ADD_MOVIE_TO_WATCH_LIST_SUCCESS =
	'ADD_MOVIE_TO_WATCH_LIST_SUCCESS';
