export const FETCH_POSTS = 'FETCH_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_REACTION = 'CREATE_REACTION';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const ADD_NEW_REACTION = 'ADD_NEW_REACTION';
