export const SAVE_MOVIE_LIST = 'SAVE_MOVIE_LIST';
export const SAVE_MOVIE_LIST_SUCCESS = 'SAVE_MOVIE_LIST_SUCCESS';
export const FETCH_MOVIE_LISTS_PREVIEW = 'FETCH_MOVIE_LISTS_PREVIEW';
export const FETCH_MOVIE_LISTS_PREVIEW_SUCCESS =
	'FETCH_MOVIE_LISTS_PREVIEW_SUCCESS';
export const DELETE_MOVIE_LIST = 'DELETE_MOVIE_LIST';
export const FETCH_MOVIE_LIST_DETAILS = 'FETCH_MOVIE_LIST_DETAILS';
export const FETCH_MOVIE_LIST_DETAILS_SUCCESS =
	'FETCH_MOVIE_LIST_DETAILS_SUCCESS';
export const FETCH_MOVIE_LIST_DETAILS_FAILURE =
	'FETCH_MOVIE_LIST_DETAILS_FAILURE';
